In [1]:
! pip install torch transformers

Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.10.0+cu128)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch) (3.24.3)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2026.2.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch) (1.3.5)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.4.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.3.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: typer>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->transformers) (0.24.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->transformers) (8.3.1)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim->transformers) (0.1.2)

In [2]:
import numpy as np
import pandas as pd

In [3]:
import torch
from transformers import AutoTokenizer, AutoModel, AutoConfig

In [38]:
df=pd.read_csv('/kaggle/input/datasets/adithip2000/genre-generalised-and-tagged/final_processed_data.csv')

In [39]:
df.head()

,Unnamed: 0,genres,form,summary
0,0,"['sci-fi', 'drama', 'family']",book,"old major, the old boar on the manor farm, cal..."
1,1,"['sci-fi', 'drama']",book,"alex, a teenager living in near-future england..."
2,2,['drama'],book,the text of the plague is divided into five pa...
3,3,"['sci-fi', 'fantasy', 'drama']",book,the novel posits that space around the milky w...
4,4,"['sci-fi', 'fantasy', 'drama', 'family']",book,"ged is a young boy on gont, one of the larger ..."

In [40]:
test_data=pd.read_csv('/kaggle/input/datasets/adithip2000/test-data/test_cmu_data.csv')
test_data.head()

,Unnamed: 0,summary,genres,form
0,0,"A heart-wrenching tale of Choma, an untouchabl...",drama,book
1,1,A poignant cinematic portrayal of an untouchab...,drama,movie
2,2,"Set in the pre-independence Malnad region, the...",drama,book
3,2,"Set in the pre-independence Malnad region, the...",history,book
4,3,A visually rich adaptation capturing the fadin...,drama,movie

In [41]:
test_data['genres'].unique()

array(['drama', 'history', 'action', 'romance', 'adventure', 'thriller',
       'crime', 'family', 'comedy'], dtype=object)

In [7]:
# genre_map = {
#     # ---------------- DRAMA ----------------
#     "fiction": "drama",
#     "novel": "drama",
#     "drama": "drama",
#     "world cinema": "drama",

#     # ---------------- COMEDY ----------------
#     "comedy": "comedy",
#     "romantic comedy": "comedy",

#     # ---------------- ROMANCE ----------------
#     "romance novel": "romance",
#     "romance": "romance",
#     "romance film": "romance",
#     "romantic drama": "romance",

#     # ---------------- ACTION ----------------
#     "action": "action",
#     "action/adventure": "action",

#     # ---------------- ADVENTURE ----------------
#     "adventure": "adventure",
#     "adventure novel": "adventure",

#     # ---------------- THRILLER ----------------
#     "thriller": "thriller",
#     "suspense": "thriller",

#     # ---------------- HORROR ----------------
#     "horror": "horror",

#     # ---------------- SCI-FI ----------------
#     "science fiction": "sci-fi",
#     "speculative fiction": "sci-fi",
#     "dystopia": "sci-fi",
#     "alternate history": "sci-fi",

#     # ---------------- FANTASY ----------------
#     "fantasy": "fantasy",

#     # ---------------- CRIME ----------------
#     "crime fiction": "crime",

#     # ---------------- MYSTERY ----------------
#     "mystery": "mystery",
#     "detective fiction": "mystery",

#     # ---------------- HISTORY ----------------
#     "historical fiction": "history",
#     "historical novel": "history",

#     # ---------------- FAMILY ----------------
#     "children's literature": "family",
#     "family film": "family",
# }

In [42]:
df.shape

(49957, 4)

In [43]:
df.columns

Index(['Unnamed: 0', 'genres', 'form', 'summary'], dtype='object')

In [44]:
test_data.columns

Index(['Unnamed: 0', 'summary', 'genres', 'form'], dtype='object')

In [45]:
df.drop(['Unnamed: 0'],inplace=True,axis=1)
test_data.drop(['Unnamed: 0'],inplace=True,axis=1)

In [46]:
# from transformers import BertTokenizer as BToken
# tokenizer=BToken.from_pretrained('bert-base-uncased')
model_id = "answerdotai/ModernBERT-base"
tokenizer = AutoTokenizer.from_pretrained(model_id)
#model = AutoModel.from_pretrained(model_id)
# Move the model to GPU if available
#device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
#model.to(device)

In [47]:
type(df['genres'].iloc[0])

str

In [48]:
df['genres'].iloc[0]

"['sci-fi', 'drama', 'family']"

In [49]:
test_data['genres'].iloc[61]

'drama'

In [50]:
import ast
df['genres']=df['genres'].apply(ast.literal_eval)

In [51]:
test_data['genres']=test_data['genres'].apply(lambda x: [x])

In [52]:
type(test_data['genres'].iloc[0])

list

In [53]:
test_data['genres'].iloc[0]

['drama']

In [54]:
label_names=sorted(df['genres'].explode().unique())

In [55]:
print(label_names)

['action', 'adventure', 'comedy', 'crime', 'drama', 'family', 'fantasy', 'history', 'horror', 'mystery', 'romance', 'sci-fi', 'thriller']

In [56]:
print(sorted(test_data['genres'].explode().unique()))

['action', 'adventure', 'comedy', 'crime', 'drama', 'family', 'history', 'romance', 'thriller']

In [57]:
from sklearn.preprocessing import MultiLabelBinarizer
mlb=MultiLabelBinarizer()
y=mlb.fit_transform(df['genres'])
print(y[0])

[0 0 0 0 1 1 0 0 0 0 0 1 0]

In [58]:
y.shape

(49957, 13)

In [59]:
y[12]

array([0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0])

In [60]:
y_test_data=mlb.transform(test_data['genres'])

In [61]:
y_test_data[1]

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0])

In [64]:
from torch.utils.data import Dataset
class GenreDataset(Dataset):
    def __init__(self, texts, labels,form,tokenizer, vectorizer, max_len=128):
        self.texts = texts
        self.labels = labels
        self.form=form
        self.tokenizer = tokenizer
        self.vectorizer = vectorizer
        self.max_len = max_len

        # 🔹 Use transform (NOT fit)
        bow_matrix = self.vectorizer.transform(self.texts)
        self.bow = torch.tensor(bow_matrix.toarray(), dtype=torch.float32)

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        text = self.texts.iloc[idx]
        label = self.labels[idx]
        form=self.form.iloc[idx]

        encoding = self.tokenizer(
            text,
            padding='max_length',
            truncation=True,
            max_length=self.max_len,
            return_tensors='pt'
        )

        return {
            "text":text,
            "form":form,
            "input_ids": encoding['input_ids'].squeeze(0),
            "attention_mask": encoding['attention_mask'].squeeze(0),
            "bow": self.bow[idx],
            "labels": torch.tensor(label, dtype=torch.float)
        }

In [65]:
label_counts=np.sum(y,axis=0)
for genre, count in zip(mlb.classes_, label_counts):
    print(genre, count)

action 6777
adventure 3599
comedy 10872
crime 5062
drama 27235
family 7090
fantasy 4426
history 1226
horror 4604
mystery 3614
romance 8919
sci-fi 7534
thriller 7925

In [66]:
total_samples=y.shape[0]
print(total_samples)

49957

In [67]:
X=df['summary']
# X=df['text']

In [69]:
X_test_data=test_data['summary']

In [70]:
from sklearn.model_selection import train_test_split as tts
X_train,X_test,Y_train,Y_test=tts(X,y,test_size=0.2,random_state=42)
X_val, X_test, Y_val, Y_test = tts(
    X_test,
    Y_test,
    test_size=0.5,
    random_state=42
)

In [71]:
print(X_train)

16256    in 2018 a prisoner named dante and his inmate ...
4204     the callum children spend their easter holiday...
6957     the enterprise is engaged in an unprecedented ...
9163     ike jerome, a 24-year-old architecture student...
14522    during a walk to the park raghuraman meets sud...
                               ...
11284    the novel continues on from the end of don't c...
44732    the film centers on themistocles and artemisia...
38158    cody weever grew up a child who loved films an...
860      the book's four main characters are ecological...
15795    the film begins with gayle, becky and judi per...
Name: summary, Length: 39965, dtype: object

In [72]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(
    max_features=8000,
    stop_words='english',
    min_df=5
)

vectorizer.fit(X_train)   # ONLY train

CountVectorizer(max_features=8000, min_df=5, stop_words='english')

In [ ]:
# train_dataset = GenreDataset(X_train, Y_train, tokenizer, vectorizer)
# val_dataset   = GenreDataset(X_val, Y_val, tokenizer, vectorizer)
# test_dataset  = GenreDataset(X_test, Y_test, tokenizer, vectorizer)

In [75]:
test_data_=GenreDataset(X_test_data,y_test_data,test_data['form'], tokenizer, vectorizer)

In [76]:
from torch.utils.data import DataLoader

In [78]:
vocab_size = len(vectorizer.get_feature_names_out())
bow_dim=vocab_size
vocab=vectorizer.get_feature_names_out()

In [92]:
test_loader = DataLoader(
    test_data_,
    batch_size=16,
    shuffle=False
)

In [93]:
len(test_loader)

4

In [80]:
import torch
import torch.nn as nn
from transformers import AutoModel

class topicGenreModel(nn.Module):
    def __init__(self, num_topics, num_genres, bow_dim, vocab_size, model_name="answerdotai/ModernBERT-base"):
        super().__init__()
        self.backbone = AutoModel.from_pretrained(model_name)
        bert_dim = self.backbone.config.hidden_size
        self.bow_weights = nn.Parameter(torch.tensor(0.1))
        
        self.context_encoder = nn.Sequential(
            nn.Linear(bert_dim, 256),
            nn.ReLU(),
            nn.Dropout(0.2)
        )
        
        self.bow_encoder = nn.Sequential(
            nn.Linear(vocab_size, 256),
            nn.ReLU(),
            nn.Dropout(0.2)
        )
        
        # 🔹 Latent space (topics)
        self.fc_mu = nn.Linear(512, num_topics)
        self.fc_logvar = nn.Linear(512, num_topics)

        # 🔹 Topic → word matrix
        self.beta = nn.Parameter(torch.randn(num_topics, vocab_size))

        # 🔹 Topic → genre
        self.classifier = nn.Sequential(
            nn.Linear(num_topics + 256, 128),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(128, num_genres)
        )

    # ---------- Encode ----------
    def encode(self, bow, embedding):
        h_ctx = torch.relu(self.context_encoder(embedding))
        alpha = torch.sigmoid(self.bow_weights)
        
        if bow is not None:
            h_bow = torch.relu(self.bow_encoder(bow))
            if self.training:
                # Dropout-like mask for BoW features
                mask = (torch.rand(h_bow.size(0), 1).to(h_bow.device) > 0.3).float()
                h_bow = h_bow * mask
            h = torch.cat([h_ctx, alpha * h_bow], dim=1)
        else:
            h_bow = torch.zeros_like(h_ctx)
            h = torch.cat([h_ctx, h_bow], dim=1)
            
        mu = self.fc_mu(h)
        logvar = self.fc_logvar(h)

        return mu, logvar, h_ctx

    # ---------- Reparameterization ----------
    def reparameterize(self, mu, logvar):
        std = torch.exp(0.5 * logvar)
        eps = torch.randn_like(std)
        return mu + eps * std

    # ---------- Decode ----------
    def decode(self, topic_dist):
        logits = torch.matmul(topic_dist, self.beta)
        return torch.softmax(logits, dim=1)

    # ---------- Forward ----------
    def forward(self, input_ids, attention_mask, bow):
        # 🔹 BERT embedding (using CLS token)
        outputs = self.backbone(
            input_ids=input_ids,
            attention_mask=attention_mask
        )
        embedding = outputs.last_hidden_state[:, 0, :]

        # 🔹 Encode
        mu, logvar, h_ctx = self.encode(bow, embedding)

        # 🔹 Sample topics
        z = self.reparameterize(mu, logvar)
        topic_dist = torch.softmax(z, dim=1)

        # 🔹 Genre prediction
        # Detaching topic distribution to prevent it from dominating the backbone gradients
        topic_dist_detached = topic_dist.detach()
        combined = torch.cat([h_ctx, 0.5 * topic_dist_detached], dim=1)
        genre_logits = self.classifier(combined)

        # 🔹 Word reconstruction
        word_dist = self.decode(topic_dist)

        return topic_dist, genre_logits, word_dist, mu, logvar

In [81]:
device=torch.device("cuda" if torch.cuda.is_available() else "cpu")

   return {
            "input_ids": encoding['input_ids'].squeeze(0),
            "attention_mask": encoding['attention_mask'].squeeze(0),
            "bow": self.bow[idx],
            "labels": torch.tensor(label, dtype=torch.float)
        }

Remember, whole batch will be processed at once from the loader

In [83]:
# vocab_size = len(vectorizer.get_feature_names_out())
# bow_dim=train_dataset.bow.shape[1]
num_genres=len(mlb.classes_)
print(f"Vocab size {vocab_size}")
print(f"bow dim {bow_dim}")
print(f"num_genres {num_genres}")
num_topics=32
print(f"num topics {num_topics}")
model=topicGenreModel(num_topics,num_genres,bow_dim,vocab_size)
state_dict=torch.load('/kaggle/input/models/adithip2000/final-ver/pytorch/default/1/checkpoint_v8_on_v7.pt',map_location=device)
model.load_state_dict(state_dict)
model.to(device)

Vocab size 8000
bow dim 8000
num_genres 13
num topics 32

model.safetensors:   0%|          | 0.00/599M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/134 [00:00<?, ?it/s]

ModernBertModel LOAD REPORT from: answerdotai/ModernBERT-base
Key               | Status     |  |
------------------+------------+--+-
decoder.bias      | UNEXPECTED |  |
head.dense.weight | UNEXPECTED |  |
head.norm.weight  | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

topicGenreModel(
  (backbone): ModernBertModel(
    (embeddings): ModernBertEmbeddings(
      (tok_embeddings): Embedding(50368, 768, padding_idx=50283)
      (norm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (drop): Dropout(p=0.0, inplace=False)
    )
    (layers): ModuleList(
      (0): ModernBertEncoderLayer(
        (attn_norm): Identity()
        (attn): ModernBertAttention(
          (Wqkv): Linear(in_features=768, out_features=2304, bias=False)
          (Wo): Linear(in_features=768, out_features=768, bias=False)
          (out_drop): Identity()
        )
        (mlp_norm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (mlp): ModernBertMLP(
          (Wi): Linear(in_features=768, out_features=2304, bias=False)
          (act): GELUActivation()
          (drop): Dropout(p=0.0, inplace=False)
          (Wo): Linear(in_features=1152, out_features=768, bias=False)
        )
      )
      (1-21): 21 x ModernBertEncoderLayer(
        (attn_norm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (attn): ModernBertAttention(
          (Wqkv): Linear(in_features=768, out_features=2304, bias=False)
          (Wo): Linear(in_features=768, out_features=768, bias=False)
          (out_drop): Identity()
        )
        (mlp_norm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (mlp): ModernBertMLP(
          (Wi): Linear(in_features=768, out_features=2304, bias=False)
          (act): GELUActivation()
          (drop): Dropout(p=0.0, inplace=False)
          (Wo): Linear(in_features=1152, out_features=768, bias=False)
        )
      )
    )
    (final_norm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
    (rotary_emb): ModernBertRotaryEmbedding()
  )
  (context_encoder): Sequential(
    (0): Linear(in_features=768, out_features=256, bias=True)
    (1): ReLU()
    (2): Dropout(p=0.2, inplace=False)
  )
  (bow_encoder): Sequential(
    (0): Linear(in_features=8000, out_features=256, bias=True)
    (1): ReLU()
    (2): Dropout(p=0.2, inplace=False)
  )
  (fc_mu): Linear(in_features=512, out_features=32, bias=True)
  (fc_logvar): Linear(in_features=512, out_features=32, bias=True)
  (classifier): Sequential(
    (0): Linear(in_features=288, out_features=128, bias=True)
    (1): ReLU()
    (2): Dropout(p=0.3, inplace=False)
    (3): Linear(in_features=128, out_features=13, bias=True)
  )
)

In [96]:
def inspect_sample(model, dataloader, vocab, label_names, device, threshold=0.2, idx=0, original_texts=None):
    
    model.eval()
    
    # Get one batch
    batch = next(iter(dataloader))
    
    # Select sample
    input_ids = batch['input_ids'][idx].unsqueeze(0).to(device)
    attention_mask = batch['attention_mask'][idx].unsqueeze(0).to(device)
    bow = batch['bow'][idx].unsqueeze(0).to(device)
    labels = batch['labels'][idx].to(device)
    text=batch['text'][idx]
    form=batch['form'][idx]
    
    with torch.no_grad():
        topic_dist, genre_logits, word_dist, mu, logvar = model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            bow=bow
        )
    
    # Predictions
    probs = torch.sigmoid(genre_logits)
    preds = (probs > threshold).int()
    
    # Convert to label names
    predicted_labels = [label_names[i] for i in range(len(label_names)) if preds[0][i] == 1]
    true_labels = [label_names[i] for i in range(len(label_names)) if labels[i] == 1]
    
    # Topic info
    topic_distribution = topic_dist[0].cpu().numpy()
    top_topic = torch.argmax(topic_dist, dim=1).item()
    
    # Top words
    def get_top_words(word_dist, vocab, top_k=10):
        top_indices = word_dist.squeeze().argsort(descending=True)[:top_k]
        return [vocab[i] for i in top_indices]
    
    top_words = get_top_words(word_dist, vocab)
    
    # Return values (useful if needed)
    return {
        "text":text,
        "form":form,
        "true_labels": true_labels,
        "predicted_labels": predicted_labels,
        "topic_distribution": topic_distribution,
        "top_topic": top_topic,
        "top_words": top_words
    }

In [94]:
for batch in test_loader:
    for i in range(0,len(batch)):
        print("=================================================")
        print(inspect_sample(
    model=model,
    dataloader=test_loader,
    vocab=vocab,
    label_names=label_names,
    device=device,
    threshold=0.5,
    idx=i,
      # optional
))

=================================================
{'text': 'A heart-wrenching tale of Choma, an untouchable bonded laborer whose only solace is playing his drum, as he struggles against the oppressive caste system in a rural village.', 'form': 'book', 'true_labels': ['drama'], 'predicted_labels': ['drama'], 'topic_distribution': array([0.00588725, 0.00716426, 0.01942398, 0.01781542, 0.00464861,
       0.04672855, 0.2872587 , 0.01033369, 0.00346397, 0.02232333,
       0.054191  , 0.01302769, 0.01937988, 0.05701146, 0.00412389,
       0.00716174, 0.08575521, 0.01469398, 0.00719179, 0.01097707,
       0.02138145, 0.01775213, 0.11316463, 0.02590611, 0.0026854 ,
       0.03538746, 0.00631462, 0.03547547, 0.01496761, 0.00652545,
       0.01355036, 0.00832783], dtype=float32), 'top_topic': 6, 'top_words': ['men', 'death', 'world', 'son', 'attempt', 'ex', 'present', 'eventually', 'friends', 'war']}
=================================================
{'text': "A poignant cinematic portrayal of an untouchable bonded laborer's tragic life, highlighting his struggles with caste prejudice, poverty, and debt, anchored by his emotional connection to his drum.", 'form': 'movie', 'true_labels': ['drama'], 'predicted_labels': ['drama'], 'topic_distribution': array([0.00867279, 0.01162777, 0.00836761, 0.00679511, 0.01076791,
       0.00264164, 0.07163608, 0.01107484, 0.04929791, 0.03058548,
       0.07332417, 0.1516953 , 0.00330982, 0.04660552, 0.01680747,
       0.0453126 , 0.0345022 , 0.03744693, 0.0583923 , 0.0093973 ,
       0.02217201, 0.06451707, 0.00685318, 0.00915099, 0.04158892,
       0.09254724, 0.00300036, 0.01647815, 0.01685053, 0.00984927,
       0.00393007, 0.02480151], dtype=float32), 'top_topic': 11, 'top_words': ['home', 'woman', 'just', 'time', 'arrives', 'parents', 'tells', 'money', 'come', 'men']}
=================================================
{'text': 'Set in the pre-independence Malnad region, the novel explores the complex dynamics, decaying feudal system, and intricate human relationships within a prominent Gowda family.', 'form': 'book', 'true_labels': ['drama'], 'predicted_labels': ['history'], 'topic_distribution': array([0.01011341, 0.03310819, 0.03183951, 0.02434385, 0.0766942 ,
       0.04532342, 0.01569271, 0.03263675, 0.06168586, 0.01095897,
       0.01309905, 0.01198955, 0.13950154, 0.04409982, 0.00515077,
       0.03332217, 0.01317401, 0.02803009, 0.0047933 , 0.01841577,
       0.05864693, 0.04290012, 0.03123359, 0.00781557, 0.0144784 ,
       0.0427756 , 0.00699814, 0.05636972, 0.00671833, 0.00778952,
       0.04078707, 0.02951404], dtype=float32), 'top_topic': 12, 'top_words': ['help', 'years', 'time', 'home', 'having', 'local', 'love', 'tells', 'mother', 'family']}
=================================================
{'text': 'Set in the pre-independence Malnad region, the novel explores the complex dynamics, decaying feudal system, and intricate human relationships within a prominent Gowda family.', 'form': 'book', 'true_labels': ['history'], 'predicted_labels': ['history'], 'topic_distribution': array([0.01635513, 0.02054414, 0.09737562, 0.0237323 , 0.07287266,
       0.00676625, 0.01726463, 0.06579511, 0.059397  , 0.01089851,
       0.02659375, 0.00438463, 0.01136578, 0.03519598, 0.01023793,
       0.05513553, 0.02975659, 0.0205101 , 0.02362633, 0.01262597,
       0.03527722, 0.06373126, 0.01160827, 0.02573084, 0.03091232,
       0.00170716, 0.00187993, 0.01201268, 0.04506516, 0.06226851,
       0.06678976, 0.02258295], dtype=float32), 'top_topic': 2, 'top_words': ['soon', 'death', 'eventually', 'tells', 'starts', 'come', 'gets', 'group', 'night', 'love']}
=================================================
{'text': 'A visually rich adaptation capturing the fading feudal glory and complex household politics of a wealthy family in the lush landscapes of the Malnad region.', 'form': 'movie', 'true_labels': ['drama'], 'predicted_labels': ['drama', 'history'], 'topic_distribution': array([0.07444151, 0.05448899, 0.03990682, 0.18908493, 0.02967869,
       0.01724989, 0.00967534, 0.00269052, 0.01466502, 0.00571245,
       0.01531221, 0.07971267, 0.01560644, 0.07279317, 0.04115222,
       0.00319283, 0.01041051, 0.00608883, 0.04808605, 0.02550369,
       0.0060388 , 0.04021726, 0.04290376, 0.04882874, 0.02713062,
       0.00201667, 0.01066267, 0.00896999, 0.03281051, 0.01125157,
       0.01073908, 0.00297754], dtype=float32), 'top_topic': 3, 'top_words': ['time', 'refuses', 'brother', 'group', 'gets', 'woman', 'men', 'run', 'death', 'love']}
=================================================
{'text': 'A visually rich adaptation capturing the fading feudal glory and complex household politics of a wealthy family in the lush landscapes of the Malnad region.', 'form': 'movie', 'true_labels': ['history'], 'predicted_labels': ['drama', 'history'], 'topic_distribution': array([0.00926655, 0.0476935 , 0.0276001 , 0.03562542, 0.0472363 ,
       0.009648  , 0.04557132, 0.0207592 , 0.02663498, 0.01053386,
       0.00326242, 0.06900686, 0.00578835, 0.08119531, 0.0563412 ,
       0.01287498, 0.01193408, 0.01988997, 0.02190164, 0.03761685,
       0.03102235, 0.01172238, 0.03470117, 0.00812222, 0.01723116,
       0.06284165, 0.00174837, 0.01397227, 0.16376139, 0.00450362,
       0.00656743, 0.04342508], dtype=float32), 'top_topic': 28, 'top_words': ['woman', 'tells', 'brother', 'finds', 'run', 'group', 'children', 'men', 'refuses', 'world']}
=================================================
{'text': 'A heart-wrenching tale of Choma, an untouchable bonded laborer whose only solace is playing his drum, as he struggles against the oppressive caste system in a rural village.', 'form': 'book', 'true_labels': ['drama'], 'predicted_labels': ['drama'], 'topic_distribution': array([0.01098926, 0.02060577, 0.08301795, 0.01949256, 0.01064914,
       0.0291714 , 0.00685518, 0.34614292, 0.03098126, 0.02102722,
       0.00841933, 0.0292643 , 0.00469008, 0.01241182, 0.02504105,
       0.01557129, 0.00769958, 0.00493913, 0.02730561, 0.00886811,
       0.02821552, 0.05268368, 0.00928405, 0.00205967, 0.01038176,
       0.0317463 , 0.009422  , 0.0377215 , 0.04007947, 0.00854392,
       0.02047069, 0.02624847], dtype=float32), 'top_topic': 7, 'top_words': ['tells', 'come', 'black', 'soon', 'eventually', 'father', 'just', 'named', 'gets', 'falls']}
=================================================
{'text': "A poignant cinematic portrayal of an untouchable bonded laborer's tragic life, highlighting his struggles with caste prejudice, poverty, and debt, anchored by his emotional connection to his drum.", 'form': 'movie', 'true_labels': ['drama'], 'predicted_labels': ['drama'], 'topic_distribution': array([0.02674386, 0.0347518 , 0.01036031, 0.00512447, 0.03193996,
       0.01670101, 0.01232959, 0.08801835, 0.0252942 , 0.02135112,
       0.02040406, 0.10514418, 0.02046107, 0.01287097, 0.02175448,
       0.00833799, 0.06399398, 0.01863337, 0.0611569 , 0.00672081,
       0.04599639, 0.00775174, 0.02069354, 0.04262295, 0.03022824,
       0.01060737, 0.01700952, 0.00802622, 0.01995848, 0.02661728,
       0.080647  , 0.0777488 ], dtype=float32), 'top_topic': 11, 'top_words': ['soon', 'come', 'time', 'eventually', 'parents', 'tells', 'just', 'daughter', 'woman', 'man']}
=================================================
{'text': 'Set in the pre-independence Malnad region, the novel explores the complex dynamics, decaying feudal system, and intricate human relationships within a prominent Gowda family.', 'form': 'book', 'true_labels': ['drama'], 'predicted_labels': ['history'], 'topic_distribution': array([0.02534742, 0.0832364 , 0.02185983, 0.00701474, 0.00520955,
       0.12992303, 0.02961093, 0.04857219, 0.00977963, 0.02673734,
       0.00992714, 0.01362419, 0.00818921, 0.05028779, 0.04782123,
       0.01895637, 0.01392589, 0.03052794, 0.00342224, 0.09025218,
       0.02344405, 0.01449622, 0.01304518, 0.02566072, 0.0492799 ,
       0.09531344, 0.00358815, 0.00951947, 0.04623163, 0.02071226,
       0.01580359, 0.00868013], dtype=float32), 'top_topic': 5, 'top_words': ['tells', 'finds', 'friends', 'father', 'home', 'local', 'earth', 'later', 'men', 'time']}
=================================================
{'text': 'Set in the pre-independence Malnad region, the novel explores the complex dynamics, decaying feudal system, and intricate human relationships within a prominent Gowda family.', 'form': 'book', 'true_labels': ['history'], 'predicted_labels': ['history'], 'topic_distribution': array([0.0288865 , 0.01186836, 0.06729974, 0.05996086, 0.02665881,
       0.01441218, 0.03571509, 0.02555815, 0.04982622, 0.01070114,
       0.06323089, 0.00792846, 0.18381771, 0.08265287, 0.01698486,
       0.01517408, 0.04162692, 0.03556674, 0.00607896, 0.01572891,
       0.0248988 , 0.02585973, 0.00678773, 0.01174403, 0.00629061,
       0.00851872, 0.01767233, 0.035628  , 0.02079299, 0.0093973 ,
       0.02551479, 0.00721759], dtype=float32), 'top_topic': 12, 'top_words': ['help', 'years', 'love', 'having', 'refuses', 'father', 'time', 'death', 'make', 'family']}
=================================================
{'text': 'A visually rich adaptation capturing the fading feudal glory and complex household politics of a wealthy family in the lush landscapes of the Malnad region.', 'form': 'movie', 'true_labels': ['drama'], 'predicted_labels': ['drama', 'history'], 'topic_distribution': array([0.08305291, 0.01043746, 0.01204012, 0.061439  , 0.06779425,
       0.06177039, 0.01971872, 0.12464552, 0.01725041, 0.0086316 ,
       0.01605976, 0.01462718, 0.00298779, 0.03375772, 0.08936042,
       0.0047767 , 0.01097941, 0.0128345 , 0.00275415, 0.00453298,
       0.00873301, 0.02724724, 0.01383849, 0.03636694, 0.03694008,
       0.07400405, 0.01312125, 0.04616087, 0.02334811, 0.01534424,
       0.03924929, 0.00619545], dtype=float32), 'top_topic': 7, 'top_words': ['tells', 'local', 'instead', 'police', 'parents', 'men', 'gets', 'time', 'run', 'home']}
=================================================
{'text': 'A visually rich adaptation capturing the fading feudal glory and complex household politics of a wealthy family in the lush landscapes of the Malnad region.', 'form': 'movie', 'true_labels': ['history'], 'predicted_labels': ['drama', 'history'], 'topic_distribution': array([0.01145886, 0.02390336, 0.12342671, 0.1089137 , 0.02051964,
       0.01214576, 0.00752343, 0.0333702 , 0.01533489, 0.01317546,
       0.03423045, 0.08099246, 0.01797717, 0.00828956, 0.00454907,
       0.02542789, 0.1084695 , 0.0638112 , 0.00456201, 0.02453472,
       0.03292859, 0.02650815, 0.06740157, 0.00441684, 0.00808496,
       0.0011089 , 0.00242879, 0.01552872, 0.00548578, 0.0194356 ,
       0.01824103, 0.05581496], dtype=float32), 'top_topic': 2, 'top_words': ['time', 'love', 'gets', 'finally', 'attempts', 'group', 'make', 'away', 'left', 'brother']}
=================================================
{'text': 'A heart-wrenching tale of Choma, an untouchable bonded laborer whose only solace is playing his drum, as he struggles against the oppressive caste system in a rural village.', 'form': 'book', 'true_labels': ['drama'], 'predicted_labels': ['drama'], 'topic_distribution': array([0.00215796, 0.0289124 , 0.00799728, 0.00718387, 0.12292898,
       0.0324909 , 0.01774844, 0.11191069, 0.00759175, 0.02582656,
       0.05619412, 0.05075467, 0.00169733, 0.04486153, 0.0068318 ,
       0.01469446, 0.05107018, 0.02275529, 0.04145934, 0.00468915,
       0.05963863, 0.01077017, 0.0285888 , 0.00633984, 0.00651646,
       0.05986823, 0.02201779, 0.04435912, 0.07504479, 0.00471148,
       0.01223546, 0.01015253], dtype=float32), 'top_topic': 4, 'top_words': ['woman', 'tells', 'just', 'eventually', 'come', 'local', 'help', 'father', 'group', 'life']}
=================================================
{'text': "A poignant cinematic portrayal of an untouchable bonded laborer's tragic life, highlighting his struggles with caste prejudice, poverty, and debt, anchored by his emotional connection to his drum.", 'form': 'movie', 'true_labels': ['drama'], 'predicted_labels': ['drama'], 'topic_distribution': array([0.00439354, 0.03423238, 0.04409283, 0.00361834, 0.00605839,
       0.04938571, 0.00944849, 0.03325132, 0.02107527, 0.00910797,
       0.00660767, 0.03641969, 0.00367251, 0.03103933, 0.03110386,
       0.0233353 , 0.01836245, 0.05502093, 0.01679865, 0.01631207,
       0.01627453, 0.02792548, 0.04107572, 0.00434983, 0.00855102,
       0.1139048 , 0.09077889, 0.03042498, 0.00361524, 0.05576318,
       0.14581065, 0.00818893], dtype=float32), 'top_topic': 30, 'top_words': ['arrives', 'does', 'police', 'tells', 'home', 'instead', 'soon', 'house', 'day', 'local']}
=================================================
{'text': 'Set in the pre-independence Malnad region, the novel explores the complex dynamics, decaying feudal system, and intricate human relationships within a prominent Gowda family.', 'form': 'book', 'true_labels': ['drama'], 'predicted_labels': ['history'], 'topic_distribution': array([0.01473494, 0.00914293, 0.03086138, 0.0441236 , 0.04661822,
       0.03875478, 0.02365528, 0.00197746, 0.05841869, 0.00552056,
       0.1228282 , 0.00524938, 0.02112406, 0.00829125, 0.01725317,
       0.01281564, 0.06984387, 0.00532193, 0.01432164, 0.01377609,
       0.02518477, 0.03297501, 0.00652772, 0.06960367, 0.10454833,
       0.00591707, 0.03756117, 0.09396638, 0.01018576, 0.02362421,
       0.00866353, 0.01660924], dtype=float32), 'top_topic': 10, 'top_words': ['help', 'death', 'just', 'left', 'group', 'wife', 'attempt', 'city', 'starts', 'time']}
=================================================
{'text': 'Set in the pre-independence Malnad region, the novel explores the complex dynamics, decaying feudal system, and intricate human relationships within a prominent Gowda family.', 'form': 'book', 'true_labels': ['history'], 'predicted_labels': ['history'], 'topic_distribution': array([0.03226455, 0.02087279, 0.03407463, 0.00485176, 0.12599653,
       0.01022346, 0.05620821, 0.01295959, 0.02467366, 0.0213447 ,
       0.0083338 , 0.11539302, 0.08655106, 0.01536002, 0.00632193,
       0.01543923, 0.02879392, 0.00799834, 0.00170307, 0.01611241,
       0.01564813, 0.00921443, 0.05675014, 0.00341415, 0.08873824,
       0.03463358, 0.01231146, 0.03482832, 0.01571559, 0.01740997,
       0.02367264, 0.04218663], dtype=float32), 'top_topic': 4, 'top_words': ['just', 'eventually', 'girlfriend', 'time', 'group', 'help', 'old', 'years', 'young', 'woman']}
=================================================
{'text': 'A visually rich adaptation capturing the fading feudal glory and complex household politics of a wealthy family in the lush landscapes of the Malnad region.', 'form': 'movie', 'true_labels': ['drama'], 'predicted_labels': ['drama', 'history'], 'topic_distribution': array([0.00431083, 0.02516342, 0.02080848, 0.09048368, 0.01770937,
       0.01324512, 0.05632856, 0.0966412 , 0.04147896, 0.02251589,
       0.01372578, 0.00800544, 0.01645887, 0.05702383, 0.00550601,
       0.01479267, 0.01544687, 0.01705796, 0.018858  , 0.03376878,
       0.03187881, 0.05410888, 0.05565724, 0.0155939 , 0.08655576,
       0.00761291, 0.00869953, 0.01681743, 0.00881321, 0.01753228,
       0.02229047, 0.08510987], dtype=float32), 'top_topic': 7, 'top_words': ['death', 'gets', 'soon', 'group', 'time', 'refuses', 'come', 'men', 'tells', 'woman']}
=================================================
{'text': 'A visually rich adaptation capturing the fading feudal glory and complex household politics of a wealthy family in the lush landscapes of the Malnad region.', 'form': 'movie', 'true_labels': ['history'], 'predicted_labels': ['drama', 'history'], 'topic_distribution': array([0.0118372 , 0.12006066, 0.0151172 , 0.01632282, 0.0264314 ,
       0.01894088, 0.00663297, 0.00853659, 0.0218449 , 0.02045375,
       0.00479664, 0.00146866, 0.06534871, 0.02661113, 0.03104926,
       0.04139639, 0.02582795, 0.04145051, 0.04612084, 0.00793645,
       0.01491869, 0.01169204, 0.06987619, 0.02861451, 0.13462046,
       0.02550207, 0.05272165, 0.01073914, 0.0208701 , 0.00513463,
       0.04181477, 0.02531084], dtype=float32), 'top_topic': 24, 'top_words': ['time', 'woman', 'soon', 'years', 'house', 'help', 'telling', 'having', 'local', 'old']}
=================================================
{'text': 'A heart-wrenching tale of Choma, an untouchable bonded laborer whose only solace is playing his drum, as he struggles against the oppressive caste system in a rural village.', 'form': 'book', 'true_labels': ['drama'], 'predicted_labels': ['drama'], 'topic_distribution': array([0.01688671, 0.05842409, 0.00461315, 0.01285853, 0.01254227,
       0.02470308, 0.06292819, 0.05192301, 0.01355872, 0.03651297,
       0.02007577, 0.01534169, 0.05148186, 0.14056797, 0.00369488,
       0.0100404 , 0.00749015, 0.06055993, 0.01343859, 0.03383612,
       0.00691555, 0.03572128, 0.00905937, 0.009794  , 0.08628366,
       0.03824148, 0.07949248, 0.01808075, 0.02305319, 0.00745904,
       0.01709264, 0.01732847], dtype=float32), 'top_topic': 13, 'top_words': ['tells', 'woman', 'refuses', 'doesn', 'come', 'father', 'home', 'later', 'new', 'time']}
=================================================
{'text': "A poignant cinematic portrayal of an untouchable bonded laborer's tragic life, highlighting his struggles with caste prejudice, poverty, and debt, anchored by his emotional connection to his drum.", 'form': 'movie', 'true_labels': ['drama'], 'predicted_labels': ['drama'], 'topic_distribution': array([0.11984827, 0.01119375, 0.01518553, 0.01828744, 0.00896141,
       0.02060016, 0.00658603, 0.01149999, 0.00965041, 0.01679121,
       0.04953513, 0.00129054, 0.07922698, 0.00471922, 0.15359932,
       0.04332902, 0.03935828, 0.02203844, 0.02915365, 0.04708481,
       0.06122693, 0.00618388, 0.0070839 , 0.0158803 , 0.01620661,
       0.03659897, 0.0382947 , 0.00971094, 0.03852168, 0.0341742 ,
       0.00327503, 0.02490328], dtype=float32), 'top_topic': 14, 'top_words': ['instead', 'local', 'family', 'called', 'tells', 'run', 'george', 'home', 'girlfriend', 'orders']}
=================================================
{'text': 'Set in the pre-independence Malnad region, the novel explores the complex dynamics, decaying feudal system, and intricate human relationships within a prominent Gowda family.', 'form': 'book', 'true_labels': ['drama'], 'predicted_labels': ['history'], 'topic_distribution': array([0.2170084 , 0.03261353, 0.01412464, 0.01280371, 0.01779916,
       0.02034468, 0.01780348, 0.00213572, 0.01023775, 0.03674805,
       0.02038188, 0.02786522, 0.05730923, 0.06238503, 0.02767887,
       0.02637035, 0.02037727, 0.00663303, 0.04577575, 0.07980216,
       0.07330494, 0.00450789, 0.04733989, 0.00772206, 0.00263813,
       0.00653288, 0.02014598, 0.02244258, 0.03360951, 0.00635086,
       0.01097462, 0.0082327 ], dtype=float32), 'top_topic': 0, 'top_words': ['refuses', 'soon', 'tells', 'left', 'time', 'friends', 'home', 'family', 'dies', 'mother']}
=================================================
{'text': 'Set in the pre-independence Malnad region, the novel explores the complex dynamics, decaying feudal system, and intricate human relationships within a prominent Gowda family.', 'form': 'book', 'true_labels': ['history'], 'predicted_labels': ['history'], 'topic_distribution': array([0.0062076 , 0.00497976, 0.0312988 , 0.07271188, 0.02170957,
       0.0690391 , 0.03455014, 0.02079691, 0.03089941, 0.02363093,
       0.0249339 , 0.02462874, 0.00416858, 0.04270158, 0.00347434,
       0.08564693, 0.07658532, 0.00512977, 0.00306615, 0.00384247,
       0.1399622 , 0.0078561 , 0.02644696, 0.03513924, 0.0446061 ,
       0.07305016, 0.01496749, 0.00804208, 0.0048108 , 0.01421903,
       0.02644053, 0.01445739], dtype=float32), 'top_topic': 20, 'top_words': ['love', 'home', 'money', 'eventually', 'goes', 'gets', 'time', 'body', 'help', 'finds']}