In [ ]:
'''# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session'''

In [2]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv('/kaggle/input/datasets/adithip2000/genre-generalised-and-tagged/book_movie_combined.csv')

In [4]:
df.head()

,Unnamed: 0,summary,genres,form,mapped_genres
0,0,"Old Major, the old boar on the Manor Farm, ca...","['sci-fi', 'drama', 'family']",book,NaN
1,1,"Alex, a teenager living in near-future Englan...","['sci-fi', 'drama']",book,NaN
2,2,The text of The Plague is divided into five p...,['drama'],book,NaN
3,3,The novel posits that space around the Milky ...,"['sci-fi', 'fantasy', 'drama']",book,NaN
4,4,"Ged is a young boy on Gont, one of the larger...","['sci-fi', 'fantasy', 'drama', 'family']",book,NaN

In [5]:
df.shape

(50048, 5)

## Removing unnecessary columns

In [8]:
df.drop(columns=['mapped_genres'],inplace=True)

In [12]:
df.drop(columns=['Unnamed: 0'],inplace=True)

In [13]:
df.head()

,summary,genres,form
0,"Old Major, the old boar on the Manor Farm, ca...","['sci-fi', 'drama', 'family']",book
1,"Alex, a teenager living in near-future Englan...","['sci-fi', 'drama']",book
2,The text of The Plague is divided into five p...,['drama'],book
3,The novel posits that space around the Milky ...,"['sci-fi', 'fantasy', 'drama']",book
4,"Ged is a young boy on Gont, one of the larger...","['sci-fi', 'fantasy', 'drama', 'family']",book

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50048 entries, 0 to 50047
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   summary  50048 non-null  object
 1   genres   50048 non-null  object
 2   form     50048 non-null  object
dtypes: object(3)
memory usage: 1.1+ MB

In [23]:
df1=df.copy()

## Fix escaped characters (Alex\'s----> Alex's)


## Fix html entities 

## &amp; → &

## &quot; → "

## &lt; → <

## normalize spaces(Removes extra space, newlines,tabs)

## Converted to lower case (use bert-base-uncased)

In [25]:
import re
import html
def clean_text(text):
    #Fix escaped character
    text = text.replace("\\'", "'")
    text = text.replace('\\"', '"')
    text = text.replace("\\n", " ")
    text = text.replace("\\t", " ")
    #Fix HTML entities
    text=html.unescape(text)
    #Normalize spaces
    text = re.sub(r'\s+', ' ', text)
    #Lowercase
    text = text.lower()
    return text.strip()

In [26]:
df['summary_clean']=df['summary'].apply(clean_text)

In [33]:
df.drop(columns=['summary'],inplace=True)

In [34]:
df.head(10)

,genres,form,summary_clean
0,"['sci-fi', 'drama', 'family']",book,"old major, the old boar on the manor farm, cal..."
1,"['sci-fi', 'drama']",book,"alex, a teenager living in near-future england..."
2,['drama'],book,the text of the plague is divided into five pa...
3,"['sci-fi', 'fantasy', 'drama']",book,the novel posits that space around the milky w...
4,"['sci-fi', 'fantasy', 'drama', 'family']",book,"ged is a young boy on gont, one of the larger ..."
5,['sci-fi'],book,"living on mars, deckard is acting as a consult..."
6,['sci-fi'],book,beginning several months after the events in b...
7,"['sci-fi', 'drama']",book,the story is told through the eyes of narrator...
8,"['sci-fi', 'drama', 'family']",book,nine years after emperor paul muad'dib walked ...
9,"['sci-fi', 'drama', 'family']",book,the situation is desperate for the bene gesser...

In [31]:
print(df.iloc[1]['summary_clean'])

alex, a teenager living in near-future england, leads his gang on nightly orgies of opportunistic, random "ultra-violence." alex's friends ("droogs" in the novel's anglo-russian slang, nadsat) are: dim, a slow-witted bruiser who is the gang's muscle; georgie, an ambitious second-in-command; and pete, who mostly plays along as the droogs indulge their taste for ultra-violence. characterized as a sociopath and a hardened juvenile delinquent, alex is also intelligent and quick-witted, with sophisticated taste in music, being particularly fond of beethoven, or "lovely ludwig van." the novel begins with the droogs sitting in their favorite hangout (the korova milkbar), drinking milk-drug cocktails, called "milk-plus", to hype themselves for the night's mayhem. they assault a scholar walking home from the public library, rob a store leaving the owner and his wife bloodied and unconscious, stomp a panhandling derelict, then scuffle with a rival gang. joyriding through the countryside in a stolen car, they break into an isolated cottage and maul the young couple living there, beating the husband and raping his wife. in a metafictional touch, the husband is a writer working on a manuscript called "a clockwork orange," and alex contemptuously reads out a paragraph that states the novel's main theme before shredding the manuscript. back at the milk bar, alex punishes dim for some crude behaviour, and strains within the gang become apparent. at home in his dreary flat, alex plays classical music at top volume while fantasizing of even more orgiastic violence. alex skips school the next day. following an unexpected visit from p.r. deltoid, his "post-corrective advisor," alex meets a pair of ten-year-old girls and takes them back to his parents' flat, where he administers hard drugs and then rapes them. that evening, alex finds his droogs in a mutinous mood. georgie challenges alex for leadership of the gang, demanding that they pull a "man-sized" job. alex quells the rebellion by slashing dim's hand and fighting with georgie, then in a show of generosity takes them to a bar, where alex insists on following through on georgie's idea to burgle the home of a wealthy old woman. the break-in starts as farce and ends in tragic pathos, as alex's attack kills the elderly woman. his escape is blocked by dim, who attacks alex, leaving him incapacitated on the front step as the police arrive. sentenced to prison for murder, alex gets a job at the wing chapel playing religious music on the stereo before and after services as well as during the singing of hymns. the prison chaplain mistakes alex's bible studies for stirrings of faith (alex is actually reading scripture for the violent passages). after alex's fellow cellmates blame him for beating a troublesome cellmate to death, he agrees to undergo an experimental behaviour-modification treatment called the ludovico technique. the technique is a form of aversion therapy in which alex receives an injection that makes him feel sick while watching graphically violent films, eventually conditioning him to suffer crippling bouts of nausea at the mere thought of violence. as an unintended consequence, the soundtrack to one of the films—beethoven's fifth symphony—renders alex unable to listen to his beloved classical music. the effectiveness of the technique is demonstrated to a group of vips, who watch as alex collapses before a walloping bully, and abases himself before a scantily-clad young woman whose presence has aroused his predatory sexual inclinations. though the prison chaplain accuses the state of stripping alex of free will, the government officials on the scene are pleased with the results and alex is released into society. since his parents are now renting his room to a lodger, alex wanders the streets and enters a public library where he hopes to learn a painless way to commit suicide. there, he accidentally encounters the old scholar he assaulted earlier in the book, who, keen on revenge, beats alex with the help of his friends. the policemen who come to alex's rescue turn out to be none other than dim and former gang rival billyboy. the two policemen take alex outside of town and beat him up. dazed and bloodied, alex collapses at the door of an isolated cottage, realizing too late that it is the house he and his droogs invaded in the first half of the story. because the gang wore masks during the assault, the writer does not recognize alex. the writer, whose name is revealed as f. alexander, shelters alex and questions him about the conditioning. during this sequence, it is revealed that mrs. alexander died from the injuries inflicted during the gang-rape, and her husband has decided to continue living "where her fragrant memory persists" despite the horrid memories. alexander, a critic of the government, hopes to use alex as a symbol of state brutality and thereby prevent the incumbent government from being re-elected. eventually, he begins to realize alex's role in the happenings of the night two years ago. one of alexander's radical associates manages to extract a confession from alex after removing him from f. alexander's home and then locks him in a flatblock near his former home. alex is then subjected to a relentless barrage of classical music, prompting him to attempt suicide by leaping from a high window. alex wakes up in hospital, where he is courted by government officials anxious to counter the bad publicity created by his suicide attempt. with alexander safely packed off to a mental institution, alex is offered a well-paying job if he agrees to side with the government. as photographers snap pictures, alex daydreams of orgiastic violence and realizes the ludovico conditioning has been reversed: "i was cured all right." in the final chapter, alex has a new trio of droogs, but he finds he is beginning to outgrow his taste for violence. a chance encounter with pete, now married and settled down, inspires alex to seek a wife and family of his own. he contemplates the likelihood of his future son being a delinquent as he was, a prospect alex views fatalistically.

## Removing {{plot}} tag

In [37]:
df[df['summary_clean'].str.contains(r'\{\{plot\}\}', case=False, na=False)]

,genres,form,summary_clean
12110,"['thriller', 'drama', 'horror']",movie,"{{plot}} the film opens in 1974, as a young gi..."
12118,['comedy'],movie,{{plot}} following the sudden death of kid's f...
12158,['horror'],movie,{{plot}} the film begins with a boy named mich...
12159,"['drama', 'romance']",movie,{{plot}} husband and wife rawdon and miranda a...
12270,['action'],movie,{{plot}} in the dasht-e-margoh desert in remot...
...,...,...,...
49620,"['comedy', 'drama']",movie,{{plot}} the film focuses on various guests st...
49633,"['horror', 'mystery']",movie,{{plot}} gp: guard post is on the frontline in...
49702,"['sci-fi', 'fantasy', 'drama']",movie,{{plot}} news reporter ichiro sakai and photog...
49779,"['sci-fi', 'comedy', 'family']",movie,{{plot}} owen baker is a 12-year-old who has b...
49819,"['action', 'sci-fi', 'thriller', 'drama']",movie,"{{plot}} in an alternate universe, people are ..."

In [42]:
import re

def remove_plot_tag(text):
    # remove {{plot}} (case insensitive)
    text = re.sub(r'\{\{\s*plot\s*\}\}', '', text, flags=re.IGNORECASE)
    return text

In [43]:
df['summary_clean'] = df['summary_clean'].apply(remove_plot_tag)

## Detect other templates like {{....}} 

## {{plot}} ,{{summary}},...

In [47]:
df['summary_clean'].str.contains(r'\{\{.*?\}\}', na=False).sum()

np.int64(2171)

In [49]:
df[df['summary_clean'].str.contains(r'\{\{.*?\}\}', na=False)].head()

,genres,form,summary_clean
12169,"['thriller', 'horror']",movie,a mexican widow receives a letter from the hig...
12172,['drama'],movie,{{expand section}} the film follows the bandin...
12183,"['comedy', 'drama', 'romance']",movie,it is spring. randy dean is a high school seni...
12210,['thriller'],movie,the story centers around johnny graham who was...
12239,['drama'],movie,two families looking to escape painful holiday...

In [50]:
#extract templates


def extract_templates(text):
    return re.findall(r'\{\{.*?\}\}', text)

df['templates'] = df['summary_clean'].apply(extract_templates)

In [55]:
all_templates = df['templates'].explode().dropna().unique()
print(all_templates)

['{{quote box}}' '{{expand section}}' '{{cquote}}' '{{cite web}}'
 '{{long plot}}' '{{cite news}}' '{{cite book}}'
 '{{plot|date"farewell my concubine study notes">{{cite web}}'
 '{{citation needed}}'
 '{{cite book |last1frank |title1974 |publisher0-913460-31-1 |page"cohen-78">{{cite book}}'
 '{{ref_label}}' '{{fact}}' '{{quote}}' '{{mdash}}'
 '{{inappropriate tone}}' '{{see also}}' '{{inr}}' '{{cite journal}}'
 '{{spaced ndash}}' '{{uss}}' '{{nihongo}}' '{{citation}}'
 '{{plot|date"mash4077couk">classic episode - goodbye, farewell and amen. mash4077.co.uk. in pierce’s first recollection, he was on a bus returning to the 4077th after a day of drinking at the beaches of incheon. he called for a bottle of whiskey to be passed back to someone who “can’t wait”; later, he is able to more accurately recall this person was a wounded soldier, and that the bottle was filled with not whiskey, but plasma. the bus then picked up some south korean refugees, followed by some wounded soldiers who brought news of an enemy patrol in the area. the bus later pulls off the road and everyone is told to stay quiet so they would not be discovered by the enemy. one woman carried a live chicken that would not stop squawking, prompting pierce to angrily admonish her to “keep that damn chicken quiet!”, after which the noise suddenly stopped. this last detail causes pierce to break down sobbing as he finally reveals the true ending of the story. when hawkeye snapped at the woman, he had told her to keep not a chicken quiet, but rather her baby. unable to keep the baby from crying, the woman made the decision to smother her own child to silence it and protect the lives of the people on the bus. upon seeing what had happened, pierce was so traumatized that he repressed the memory of what occurred. once back at camp, he attempted to operate on a patient without anesthesia, while accusing the anesthesiologist of trying to smother the patient. but it was a later incident, driving a jeep through the wall of the officers\' club and ordering a double bourbon , that caused pierce to be committed to the mental hospital. with the true memory of the events on the bus now restored to him, pierce can acknowledge the fact that he suffered a nervous breakdown, and was in the process of writing his father that he might be coming home soon as he doubted the army would let a surgeon operate "whose cheese has slipped off his cracker". but freedman, deciding that pierce is ready to be released, sends him back to the 4077th promising to check up on him periodically. back at the 4077th, an out-of-control tank runs over the camp latrines, forcing maj. charles winchester to go to a temporary facility down the road to relieve himself. encountering a raggedy group of five chinese soldiers on a motorcycle, he is greatly surprised when they “surrender” and follow him back to camp, playing musical instruments. capt. b.j. hunnicutt takes possession of the motorcycle and later annoys winchester by painting it yellow. winchester, irritated that he is about to miss his chance to win a coveted position at a hospital in boston, consoles himself by conducting the chinese musicians in rehearsals of one of his favorite mozart works (the first movement of the [[clarinet quintet . on the surface, he is irritated with them over their inability to play the piece correctly, but he is actually bonding with and growing quite fond of them. maj. margaret houlihan learns of his situation and puts in a good word with the boston hospital’s board, but her efforts earn his ire when he finds out about them. with the crashed tank still in the camp and col. sherman potter under orders not to have it moved for the time being, enemy forces begin a mortar assault against the 4077th. several pows, locked in a makeshift pen in the compound, are unable to get to safety until father francis mulcahy lets them out. in the process, a mortar round explodes, knocking him out and leaving him with severe hearing loss . only hunnicutt knows about mulcahy’s condition, and mulcahy begs him not to tell anyone else, as it could result in his being sent home, unable to help the local orphans. shortly before pierce returns from the mental hospital, hunnicutt receives his discharge papers and leaves for home. just as he is boarding a chopper, sgt. max klinger shows potter a just-arrived set of orders that rescinds the discharge, but potter cannot hear klinger over the chopper. the shorthanded operating-room staff is soon swamped with patients, and potter calls headquarters to get another surgeon to replace hunnicutt. pierce, arriving after hunnicutt\'s departure, is upset that his roommate left without saying goodbye, much as his old friend trapper john mcintyre had. shortly afterward, during another barrage of enemy shelling, pierce drives the crashed tank through the newly built latrine and into the camp’s garbage dump to draw the shelling away from the camp. this impulsive action by pierce, coming on the heels of his breakdown, prompts potter to call freedman in for another talk with pierce. in the meantime, a korean refugee from a previous episode, soon-lee han, is still on the base and trying to find her parents. klinger becomes worried when he learns that she has left to find them, and the two realize that they have feelings for one another. they decide to get married, but much to klinger\'s frustration soon-lee insists that she cannot leave korea until she finds her family. a north korean incendiary bomb attack causes wildfires in the adjacent forest, and potter orders the 4077th to "bug out." . as soon as the camp is up and running again in its new location, potter gets the replacement surgeon he asked for—hunnicutt, whose travel plans were delayed just long enough for him to find out about his rescinded discharge. meeting up with pierce, hunnicutt says that he had meant to leave a note for him, but had no time to do so. the 4077th throws a party for hunnicutt, who had intended to be home in time for his daughter’s second birthday, and for a local orphan girl who is about that age. seeing many children at the party, pierce becomes withdrawn and tries to slip away, but freedman, who shows up during the festivities, reassures him. he considers pierce\'s commandeering of the tank to be a sensible action that took his fellow soldiers out of danger. pierce’s feelings about the thought of a patient under his care not surviving, freedman says, may make him an even better doctor than he already is. winchester eventually has to say goodbye to the chinese musicians, who are to be part of a pow exchange. as they are driven away, they finally play the mozart piece correctly for him. a public-address announcement then broadcasts the news that a truce has been signed; a cease-fire will go into effect at 10:00 that night, officially ending the hostilities. but the celebration is short-lived, as potter orders the camp moved back to its original site so the remaining wounded can be treated. among the wounded is one of the musicians, barely alive after the truck carrying the pows was shelled. none of the other four survived, and this one soon dies as well. a shaken winchester retires to his tent, where he plays a record of the mozart piece they were rehearsing, then angrily yanks it from the turntable and smashes it. in the operating room, hawkeye finds himself about to operate on a child and hesitates at first. when potter offers to switch patients with him, he declines and goes to work, indicating that his recovery is complete. freedman, his work now completed, leaves the 4077 with the same parting line he used during one of his first visits: “ladies and gentlemen, take my advice. pull down your pants and slide on the ice.” the radio announcer mentions hostilities in vietnam, to which a surgeon asks "where\'s that?". the staff continues operating throughout the night, stopping only briefly to take note when 10:00 pm comes and the guns fall silent as heard in a radio broadcast over the loudspeaker. once all the wounded have been cared for, the staff throws a final party in the mess tent, with many characters commenting on their future plans. among the main cast, potter looks forward to rejoining his wife in missouri and becoming a “semi-retired country doctor”; houlihan has rejected several overseas postings in favor of working at a big-city hospital in the united states; mulcahy decides to begin ministering to the deaf; pierce wants to take some time off, then go back to work where he can get to know his patients; and hunnicutt jokes about running off with a girl he met during his travel delay, then says he will return home to his family in san francisco. winchester has won the position he wanted at the boston hospital and agrees to accept it, despite houlihan\'s "meddling," but remarks that the music that he had loved and used as a refuge from the experience will now serve as a reminder of the deaths of the chinese musicians and the war itself. the big surprise of the evening comes from klinger, who announces his intent to marry soon-lee and stay in korea to help find her family. the wedding takes place the next morning, with mulcahy officiating, potter as best man, and houlihan as matron of honor . after the ceremony, the staff begins tearing down the camp and prepares to move out by various means. the mileage signs to everyone’s hometowns are pulled off the long-standing signpost and taken home by their respective owners, and the officers say their goodbyes as the last pieces of the camp are dismantled. mulcahy and houlihan travel to the 8063rd mash, a stopover on the way back to the states. winchester cannot find room in houlihan’s jeep, so he sends sgt. rizzo to get him another ride; he then makes peace with her and allows her to keep a treasured book she borrowed from him. just before leaving the camp, houlihan receives hugs from various members of the unit and also engages in a long, passionate goodbye kiss with pierce. the last available vehicle is a garbage truck, which winchester boards after saying goodbye. before potter rides away to the local orphanage on his beloved horse, sophie, planning to leave her there and take a jeep, pierce and hunnicutt offer him a small token of gratitude: a salute, which they seldom performed for anyone. the colonel emotionally returns the salute and rides off. pierce and hunnicutt, the last to leave, find it difficult to part. as they reminisce over their shared time, pierce laments that they will probably never see each other again, though hunnicutt insists that someday they will. the latter rides off on his motorcycle, shouting that he left a note this time. only after pierce’s helicopter has lifted off does he see this note: the word goodbye spelled out in stones on the ground. pierce smiles as he flies away from the former site of the 4077th. {{-}}'
 '{{-}}' '{{unreferenced section}}' '{{rp}}' '{{what}}' '{{incomplete}}'
 '{{refimprove}}' '{{space}}' "{{'s}}" "{{'}}" '{{hook}}' '{{cn}}'
 '{{inuniverse}}' '{{multiple image}}'
 '{{cite web|lastneil |urltwists of terror - tv movie - cast & credits - listings - nytimes.com |publisher |accessdate"martinneufeld1"/> "stolen moments" shows a shy and pretty cindy craig who has trouble meeting men, living her life in an apartment with a plethora of plants. one evening she goes to a bar and is picked up by two men, they go back to an abandoned house and have sex, but then she murders them and resumes her life as the \'quiet\' woman she is.{{cite web}}'
 '{{harvnb|eisenstein|1972| p"bordwell203" /> if true, these details were never communicated to the sinclairs, who simply found themselves with recurring requests for additional funding as eisenstein\'s vision expanded, with no attempt by eisenstein to respect the economic realities involved in making such an epic work and the financial and emotional limitations of his producers, his contract obligations, and his inability or unwillingness to cogently communicate to them before acquiring permission to proceed away from those contract obligations. this was the ultimate legacy of the film and would be repeated in the similarly aborted soviet eisenstein project, bezhin meadow. in alexandrov\'s 1979 version, which attempts to be as faithful as possible to eisenstein\'s original vision, the film unfolds as follows: ;prologue set in the time of the maya civilization in yucatán. ;sandunga life including marriage and motherhood in tehuantepec. it follows the courtship involving a golden necklace as a dowry, and eventual marriage, of a concepción and abundio.{{harvnb}}'
 '{{harvnb}}' '{{not a typo}}' '{{babylon5tvmovies}}' '{{explain}}'
 '{{cite web|lastbruce|titlehttp://movies.nytimes.com/movie/53914/the-westerner/overview the new york times|accessdate"nytimes2">{{cite web}}'
 '{{cleanup}}' '{{tone}}' '{{clarify}}' '{{see}}' '{{overly detailed}}'
 '{{imdb title}}' '{{convert}}' '{{fi icon}}' '{{original research}}'
 '{{main}}' '{{essay-like}}'
 '{{cite web|last|titlehttp://themave.com/cooper/filmog/cowblady2.htm coop: a tribute|accessdate"classic">{{cite web}}'
 '{{ro icon}}' '{{who}}' '{{hms}}' '{{hmnzs}}' '{{dead link}}'
 '{{cleanup-rewrite}}' '{{pt icon}}' '{{unreferenced}}' '{{frac}}'
 '{{in-universe}}' '{{further2}}' '{{listen}}' '{{empty section}}'
 '{{quotation}}' '{{episode list}}' '{{anchor}}' '{{nihongo3}}' '{{refn}}'
 '{{confusing}}' '{{amg movie}}' '{{prose}}' '{{de icon}}' '{{longplot}}'
 '{{story}}' '{{inrconvert}}' '{{clear}}' '{{citation broken}}'
 '{{quality}}' '{{citeweb}}' '{{lang}}'
 '{{expand section|date5819 “overview: lem hawkins’ confession,” turner classic movies]j. ronald green, straight lick, {{expand section}}'
 '{{no_icon}}' '{{sms}}' '{{unclear}}' '{{rotten-tomatoes}}' '{{dn}}'
 '{{no plot}}' '{{plot|date{{nihongo}}'
 "{{plot|dateintrostory mladen is a young professional residing in belgrade where he works as construction engineer in a decrepit state-owned company that's undergoing the process of privatization. he drives a beat-up renault 4 and rents an apartment with his wife marija who teaches english in a primary school. together they're raising their only child—an 8-year-old boy named nemanja . despite their limited means, they're still managing to make ends meet and provide for their son. they arrange and lead a fairly normal and happy family life—cheering nemanja on at swim meets and taking him to the local playground where mladen becomes acquainted with their blonde neighbour who also brings her daughter to play there. however, everything drastically changes one day when nemanja is rushed to the hospital following a collapse at gym class in school. after undergoing emergency reanimation, he is diagnosed with a heart muscle condition that requires immediate surgery since the next inflammation that could come at any time might be fatal. they are further informed by dr. lukić , that the procedure is only performed at a clinic in berlin, germany, costs {{€}}"
 '{{€}}' '{{bfidb title}}' '{{emdash}}' '{{okina}}' '{{!}}'
 '{{internet archive film}}' '{{deletable image-caption}}'
 '{{cite web|urlk&p_dataidmy bride my love |publisher"cine 21">{{cite web}}'
 '{{seealso}}' '{{says who}}' '{{infobox album}}' '{{yakuza chronology}}'
 '{{indian rupee}}' '{{disambiguation needed}}' '{{advert}}' '{{stack}}'
 '{{location map+}}' '{{location map}}' '{{hatnote}}' '{{wikiquote}}'
 '{{by whom}}' '{{ship}}' '{{mainlist}}' '{{japanese episode list}}'
 '{{es}}' '{{cquote2}}' '{{cleanup-section}}' '{{right}}' '{{samp}}'
 '{{citenews}}' '{{clarification needed}}'

In [57]:
#removing only simple templates {{cite}},{{cleanup}}
def remove_simple_templates(text):
    return re.sub(r'\{\{\s*[a-zA-Z ]+\s*\}\}', '', text)

In [58]:
df['summary_clean']=df['summary_clean'].apply(remove_simple_templates)

In [60]:
df['summary_clean'].str.contains(r'\{\{.*?\}\}', na=False).sum()

np.int64(115)

In [61]:
df['templates'] = df['summary_clean'].apply(extract_templates)
all_templates = df['templates'].explode().dropna().unique()
print(all_templates)

['{{ref_label}}'
 '{{plot|date"mash4077couk">classic episode - goodbye, farewell and amen. mash4077.co.uk. in pierce’s first recollection, he was on a bus returning to the 4077th after a day of drinking at the beaches of incheon. he called for a bottle of whiskey to be passed back to someone who “can’t wait”; later, he is able to more accurately recall this person was a wounded soldier, and that the bottle was filled with not whiskey, but plasma. the bus then picked up some south korean refugees, followed by some wounded soldiers who brought news of an enemy patrol in the area. the bus later pulls off the road and everyone is told to stay quiet so they would not be discovered by the enemy. one woman carried a live chicken that would not stop squawking, prompting pierce to angrily admonish her to “keep that damn chicken quiet!”, after which the noise suddenly stopped. this last detail causes pierce to break down sobbing as he finally reveals the true ending of the story. when hawkeye snapped at the woman, he had told her to keep not a chicken quiet, but rather her baby. unable to keep the baby from crying, the woman made the decision to smother her own child to silence it and protect the lives of the people on the bus. upon seeing what had happened, pierce was so traumatized that he repressed the memory of what occurred. once back at camp, he attempted to operate on a patient without anesthesia, while accusing the anesthesiologist of trying to smother the patient. but it was a later incident, driving a jeep through the wall of the officers\' club and ordering a double bourbon , that caused pierce to be committed to the mental hospital. with the true memory of the events on the bus now restored to him, pierce can acknowledge the fact that he suffered a nervous breakdown, and was in the process of writing his father that he might be coming home soon as he doubted the army would let a surgeon operate "whose cheese has slipped off his cracker". but freedman, deciding that pierce is ready to be released, sends him back to the 4077th promising to check up on him periodically. back at the 4077th, an out-of-control tank runs over the camp latrines, forcing maj. charles winchester to go to a temporary facility down the road to relieve himself. encountering a raggedy group of five chinese soldiers on a motorcycle, he is greatly surprised when they “surrender” and follow him back to camp, playing musical instruments. capt. b.j. hunnicutt takes possession of the motorcycle and later annoys winchester by painting it yellow. winchester, irritated that he is about to miss his chance to win a coveted position at a hospital in boston, consoles himself by conducting the chinese musicians in rehearsals of one of his favorite mozart works (the first movement of the [[clarinet quintet . on the surface, he is irritated with them over their inability to play the piece correctly, but he is actually bonding with and growing quite fond of them. maj. margaret houlihan learns of his situation and puts in a good word with the boston hospital’s board, but her efforts earn his ire when he finds out about them. with the crashed tank still in the camp and col. sherman potter under orders not to have it moved for the time being, enemy forces begin a mortar assault against the 4077th. several pows, locked in a makeshift pen in the compound, are unable to get to safety until father francis mulcahy lets them out. in the process, a mortar round explodes, knocking him out and leaving him with severe hearing loss . only hunnicutt knows about mulcahy’s condition, and mulcahy begs him not to tell anyone else, as it could result in his being sent home, unable to help the local orphans. shortly before pierce returns from the mental hospital, hunnicutt receives his discharge papers and leaves for home. just as he is boarding a chopper, sgt. max klinger shows potter a just-arrived set of orders that rescinds the discharge, but potter cannot hear klinger over the chopper. the shorthanded operating-room staff is soon swamped with patients, and potter calls headquarters to get another surgeon to replace hunnicutt. pierce, arriving after hunnicutt\'s departure, is upset that his roommate left without saying goodbye, much as his old friend trapper john mcintyre had. shortly afterward, during another barrage of enemy shelling, pierce drives the crashed tank through the newly built latrine and into the camp’s garbage dump to draw the shelling away from the camp. this impulsive action by pierce, coming on the heels of his breakdown, prompts potter to call freedman in for another talk with pierce. in the meantime, a korean refugee from a previous episode, soon-lee han, is still on the base and trying to find her parents. klinger becomes worried when he learns that she has left to find them, and the two realize that they have feelings for one another. they decide to get married, but much to klinger\'s frustration soon-lee insists that she cannot leave korea until she finds her family. a north korean incendiary bomb attack causes wildfires in the adjacent forest, and potter orders the 4077th to "bug out." . as soon as the camp is up and running again in its new location, potter gets the replacement surgeon he asked for—hunnicutt, whose travel plans were delayed just long enough for him to find out about his rescinded discharge. meeting up with pierce, hunnicutt says that he had meant to leave a note for him, but had no time to do so. the 4077th throws a party for hunnicutt, who had intended to be home in time for his daughter’s second birthday, and for a local orphan girl who is about that age. seeing many children at the party, pierce becomes withdrawn and tries to slip away, but freedman, who shows up during the festivities, reassures him. he considers pierce\'s commandeering of the tank to be a sensible action that took his fellow soldiers out of danger. pierce’s feelings about the thought of a patient under his care not surviving, freedman says, may make him an even better doctor than he already is. winchester eventually has to say goodbye to the chinese musicians, who are to be part of a pow exchange. as they are driven away, they finally play the mozart piece correctly for him. a public-address announcement then broadcasts the news that a truce has been signed; a cease-fire will go into effect at 10:00 that night, officially ending the hostilities. but the celebration is short-lived, as potter orders the camp moved back to its original site so the remaining wounded can be treated. among the wounded is one of the musicians, barely alive after the truck carrying the pows was shelled. none of the other four survived, and this one soon dies as well. a shaken winchester retires to his tent, where he plays a record of the mozart piece they were rehearsing, then angrily yanks it from the turntable and smashes it. in the operating room, hawkeye finds himself about to operate on a child and hesitates at first. when potter offers to switch patients with him, he declines and goes to work, indicating that his recovery is complete. freedman, his work now completed, leaves the 4077 with the same parting line he used during one of his first visits: “ladies and gentlemen, take my advice. pull down your pants and slide on the ice.” the radio announcer mentions hostilities in vietnam, to which a surgeon asks "where\'s that?". the staff continues operating throughout the night, stopping only briefly to take note when 10:00 pm comes and the guns fall silent as heard in a radio broadcast over the loudspeaker. once all the wounded have been cared for, the staff throws a final party in the mess tent, with many characters commenting on their future plans. among the main cast, potter looks forward to rejoining his wife in missouri and becoming a “semi-retired country doctor”; houlihan has rejected several overseas postings in favor of working at a big-city hospital in the united states; mulcahy decides to begin ministering to the deaf; pierce wants to take some time off, then go back to work where he can get to know his patients; and hunnicutt jokes about running off with a girl he met during his travel delay, then says he will return home to his family in san francisco. winchester has won the position he wanted at the boston hospital and agrees to accept it, despite houlihan\'s "meddling," but remarks that the music that he had loved and used as a refuge from the experience will now serve as a reminder of the deaths of the chinese musicians and the war itself. the big surprise of the evening comes from klinger, who announces his intent to marry soon-lee and stay in korea to help find her family. the wedding takes place the next morning, with mulcahy officiating, potter as best man, and houlihan as matron of honor . after the ceremony, the staff begins tearing down the camp and prepares to move out by various means. the mileage signs to everyone’s hometowns are pulled off the long-standing signpost and taken home by their respective owners, and the officers say their goodbyes as the last pieces of the camp are dismantled. mulcahy and houlihan travel to the 8063rd mash, a stopover on the way back to the states. winchester cannot find room in houlihan’s jeep, so he sends sgt. rizzo to get him another ride; he then makes peace with her and allows her to keep a treasured book she borrowed from him. just before leaving the camp, houlihan receives hugs from various members of the unit and also engages in a long, passionate goodbye kiss with pierce. the last available vehicle is a garbage truck, which winchester boards after saying goodbye. before potter rides away to the local orphanage on his beloved horse, sophie, planning to leave her there and take a jeep, pierce and hunnicutt offer him a small token of gratitude: a salute, which they seldom performed for anyone. the colonel emotionally returns the salute and rides off. pierce and hunnicutt, the last to leave, find it difficult to part. as they reminisce over their shared time, pierce laments that they will probably never see each other again, though hunnicutt insists that someday they will. the latter rides off on his motorcycle, shouting that he left a note this time. only after pierce’s helicopter has lifted off does he see this note: the word goodbye spelled out in stones on the ground. pierce smiles as he flies away from the former site of the 4077th. {{-}}'
 '{{-}}' "{{'s}}" "{{'}}" '{{babylon5tvmovies}}' '{{essay-like}}'
 '{{cleanup-rewrite}}' '{{in-universe}}' '{{further2}}' '{{nihongo3}}'
 '{{no_icon}}' '{{rotten-tomatoes}}'
 "{{plot|dateintrostory mladen is a young professional residing in belgrade where he works as construction engineer in a decrepit state-owned company that's undergoing the process of privatization. he drives a beat-up renault 4 and rents an apartment with his wife marija who teaches english in a primary school. together they're raising their only child—an 8-year-old boy named nemanja . despite their limited means, they're still managing to make ends meet and provide for their son. they arrange and lead a fairly normal and happy family life—cheering nemanja on at swim meets and taking him to the local playground where mladen becomes acquainted with their blonde neighbour who also brings her daughter to play there. however, everything drastically changes one day when nemanja is rushed to the hospital following a collapse at gym class in school. after undergoing emergency reanimation, he is diagnosed with a heart muscle condition that requires immediate surgery since the next inflammation that could come at any time might be fatal. they are further informed by dr. lukić , that the procedure is only performed at a clinic in berlin, germany, costs {{€}}"
 '{{€}}' '{{!}}' '{{deletable image-caption}}' '{{location map+}}'
 '{{cquote2}}' '{{cleanup-section}}' '{{ipa-gd}}' '{{\'"}}'
 '{{pov-section}}' '{{stub-section}}' '{{col-begin}}' '{{col-3}}'
 '{{col-end}}' '{{?}}' '{{by whom?}}' '{{ipac-en}}' '{{huh?}}'
 '{{section-incomplete}}' '{{weasel-inline}}' '{{" \'}}' '{{bibleref2c}}'
 '{{expand-section}}' '{{citation needed|datecorren>{{swe_icon}}'
 '{{s-start}}' '{{s-end}}' '{{??}}' '{{inflation-fn}}' '{{how?}}'
 '{{co2}}' '{{’}}' '{{copy edit-section}}']

In [63]:
#extract plot text {{plot |....}}
def extract_plot_content(text):
    match = re.search(r'\{\{plot\|.*?"(.*?)\}\}', text, flags=re.DOTALL)
    if match:
        return match.group(1)
    return text

In [64]:
df['summary_clean'] = df['summary_clean'].apply(extract_plot_content)

In [66]:
#remove remaining templates
def remove_all_templates(text):
    return re.sub(r'\{\{.*?\}\}', '', text)

In [67]:
df['summary_clean'] = df['summary_clean'].apply(remove_all_templates)

In [68]:
df['summary_clean'].str.contains(r'\{\{.*?\}\}', na=False).sum()

np.int64(0)

In [69]:
df['templates'] = df['summary_clean'].apply(extract_templates)
all_templates = df['templates'].explode().dropna().unique()
print(all_templates)

[]

In [118]:
#check if any summary is empty
(df['summary_clean'].str.strip() == '').sum()

np.int64(0)

In [75]:
print(df['summary_clean'].iloc[12239])

two families looking to escape painful holiday memories take a vacation to an exotic caribbean island over christmas. a widowed mother, dana , and her two sons, chris and michael meet a divorced father, dan ([[colin ferguson , and his two daughters, blair and nell when their cruise ship docks in puerto rico. despite a rough start, the parents and kids begin to develop bonds over the course of their stay at a beautiful puerto rican beach resort. it looks like an idyllic brady bunch holiday for the two families as dana and dan try to put their personal tragedies behind them and begin to grow closer, until an unexpected visitor from the past appears and threatens their tentative romance. what promised to be a joyous christmas filled with fresh hope and new relationships turns complicated as each member of the two families must sort out their feelings and choose their own path.

In [78]:
df.drop(columns=['templates'],inplace=True)

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50048 entries, 0 to 50047
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   genres         50048 non-null  object
 1   form           50048 non-null  object
 2   summary_clean  50048 non-null  object
dtypes: object(3)
memory usage: 1.1+ MB

,genres,form,summary_clean
33217,"['thriller', 'drama', 'crime']",movie,former cop billy taggart begins following the ...
22636,['sci-fi'],movie,"in a remote arctic research station, governmen..."
9726,"['sci-fi', 'drama']",book,"the tale begins with two college-age brothers,..."
36952,"['action', 'adventure']",movie,"an aging, respected commander paul blanchard, ..."
2047,['romance'],book,"the son of the duke and duchess of avon, the m..."
9133,"['drama', 'romance']",book,harry silver is a successful television produc...
9137,['sci-fi'],book,"the main character, sir charles ravenstreet, i..."
23839,"['action', 'drama', 'family']",movie,"sora, umi and ao are three school-aged girls w..."
17083,"['sci-fi', 'action']",movie,{{ref improve section|datepart onephoto of mai...
8152,"['sci-fi', 'thriller', 'drama', 'mystery']",book,~plot outline description~ --> <!--

In [85]:
print(df.iloc[17083]['summary_clean'])

{{ref improve section|datepart onephoto of main characters|the first two primary characters of half-life: escape from city 17, potrayed by derek chan and ian purchase. the citadel can be seen in the background.]] --> part one is set during the second half of events of half-life 2: episode one. dr. isaac kleiner is making his "kleinercasts" on city 17's pa system, warning that the combine citadel is set to explode at any moment; should the citadel detonate, the resulting explosion will destroy the city and the surrounding area. prior to the film's events, gordon freeman's actions within the citadel have held down the impending explosion, opening a small window of time for civilians to escape. members of the lambda resistance are seen fighting their way out of the city as the combine's civil protection forces try to hold them back. cp officers are also seen executing captured rebels, while combine synths wreak havoc on the warzone. two male resistance members are introduced escaping through an overrun trainyard. through radio communication, the two learn from a third rebel that the last evacuation train has already left, and are urged to escape the city on foot through the canal system in order to catch up with david, who is en route to the resistance stronghold of white forest. after a brief argument, the two resolve to escape city 17 before "the citadel blows us up first". suddenly, cp officers appear and fire on the resistance members. the two retaliate with their own weaponry and manage to escape. they are eventually caught upon an open stretch of railway, where a hunter-chopper appears and fires at them, giving chase. the duo disappear behind a cloud of dirt from the wake of the chopper's mounted gun, and the film abruptly cuts to black.

In [86]:
print(df.iloc[8152]['summary_clean'])

~plot outline description~ --> <!--

## Checking problematic rows  {{ ......

In [88]:
mask = df['summary_clean'].str.startswith('{{', na=False)
print(mask.sum())

66

In [90]:
df[mask]['form'].value_counts()

form
movie    66
Name: count, dtype: int64

In [91]:
df[mask]['genres'].explode().value_counts().head()

genres
['drama']               5
['comedy']              4
['drama', 'romance']    3
['comedy', 'drama']     3
['comedy', 'family']    3
Name: count, dtype: int64

In [93]:
# only 66 rows are there so removing them 

mask = df['summary_clean'].str.startswith('{{', na=False)
df = df[~mask]

In [94]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 49982 entries, 0 to 50047
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   genres         49982 non-null  object
 1   form           49982 non-null  object
 2   summary_clean  49982 non-null  object
dtypes: object(3)
memory usage: 1.5+ MB

In [95]:
df.shape

(49982, 3)

## Checking HTML comments /summary starting with plot outline and removing them

In [115]:
#25 rows removed
mask = (
    df['summary_clean'].str.contains('plot outline', case=False, na=False) |
    df['summary_clean'].str.contains(r'<!--.*?-->', na=False)
)

df = df[~mask]

In [117]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 49957 entries, 0 to 50047
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   genres         49957 non-null  object
 1   form           49957 non-null  object
 2   summary_clean  49957 non-null  object
dtypes: object(3)
memory usage: 1.5+ MB

In [122]:
df.sample(10)

,genres,form,summary_clean
9966,['sci-fi'],book,the story follows the heroic jedi knights as t...
12517,"['sci-fi', 'thriller', 'action']",movie,houston cop jack caine does not let police pro...
34245,['comedy'],movie,italian election day in the early '80s. three ...
42525,"['sci-fi', 'action', 'family']",movie,green legend is set in a science fiction-style...
3906,"['thriller', 'drama', 'mystery', 'crime']",book,stephanie is assigned to bring in semi-retired...
24479,"['thriller', 'drama', 'mystery']",movie,jennifer peters attempts to save her brother r...
23917,"['action', 'drama', 'romance', 'comedy']",movie,"in 1914, american showgirl ""suzy"" trent is in ..."
35435,['comedy'],movie,duane balfour ([[douglas smith was born into a...
43012,['crime'],movie,ed hutcheson is the crusading managing editor ...
1136,"['drama', 'family']",book,"gene forrester, the protagonist, returns to hi..."

In [120]:
df.to_csv("clean_dataset.csv", index=False, encoding='utf-8')