In [1]:
import numpy as np
import pandas as pd

In [2]:
df_book=pd.read_csv('/kaggle/input/datasets/adithip2000/cmu-dataset/books.csv')
df_movie=pd.read_csv('/kaggle/input/datasets/adithip2000/cmu-dataset/movies.csv')

In [3]:
df_book.head()

,title,genres,summary
0,Animal Farm,"['Roman à clef', 'Satire', ""Children's literat...","Old Major, the old boar on the Manor Farm, ca..."
1,A Clockwork Orange,"['Science Fiction', 'Novella', 'Speculative fi...","Alex, a teenager living in near-future Englan..."
2,The Plague,"['Existentialism', 'Fiction', 'Absurdist ficti...",The text of The Plague is divided into five p...
3,A Fire Upon the Deep,"['Hard science fiction', 'Science Fiction', 'S...",The novel posits that space around the Milky ...
4,All Quiet on the Western Front,"['War novel', 'Roman à clef']","The book tells the story of Paul Bäumer, a Ge..."

In [4]:
df_book.shape

(12841, 3)

In [5]:
df_movie.head(5)

,id,plot,name,Genre
0,23890098,"Shlykov, a hard-working taxi driver and Lyosha...",Taxi Blues,"['Drama', 'World cinema']"
1,31186339,The nation of Panem consists of a wealthy Capi...,The Hunger Games,"['Action/Adventure', 'Science Fiction', 'Actio..."
2,20663735,Poovalli Induchoodan is sentenced for six yea...,Narasimham,"['Musical', 'Action', 'Drama', 'Bollywood']"
3,2231378,"The Lemon Drop Kid , a New York City swindler,...",The Lemon Drop Kid,"['Screwball comedy', 'Comedy']"
4,595909,Seventh-day Adventist Church pastor Michael Ch...,A Cry in the Dark,"['Crime Fiction', 'Drama', 'Docudrama', 'World..."

In [6]:
df_movie.shape

(42204, 4)

In [7]:
print(df_book['genres'].iloc[0])
print(type(df_book['genres'].iloc[0]))

['Roman à clef', 'Satire', "Children's literature", 'Speculative fiction', 'Fiction']
<class 'str'>

In [8]:
print(df_movie['Genre'].iloc[0])
print(type(df_movie['Genre'].iloc[0]))

['Drama', 'World cinema']
<class 'str'>

In [9]:
import ast
df_book['genres']=df_book['genres'].apply(ast.literal_eval)

In [10]:
df_movie['Genre']=df_movie['Genre'].apply(ast.literal_eval)

In [11]:
df_book['genres'] = df_book['genres'].apply(
    lambda x: [g.lower().strip() for g in x]
)

In [12]:
df_movie['Genre'] = df_movie['Genre'].apply(
    lambda x: [g.lower().strip() for g in x]
)

In [13]:
book_genres_exploded = df_book.explode('genres')
movie_genres_exploded = df_movie.explode('Genre')

In [14]:
book_genres_exploded.head()

,title,genres,summary
0,Animal Farm,roman à clef,"Old Major, the old boar on the Manor Farm, ca..."
0,Animal Farm,satire,"Old Major, the old boar on the Manor Farm, ca..."
0,Animal Farm,children's literature,"Old Major, the old boar on the Manor Farm, ca..."
0,Animal Farm,speculative fiction,"Old Major, the old boar on the Manor Farm, ca..."
0,Animal Farm,fiction,"Old Major, the old boar on the Manor Farm, ca..."

In [15]:
movie_genres_exploded.head(10)

,id,plot,name,Genre
0,23890098,"Shlykov, a hard-working taxi driver and Lyosha...",Taxi Blues,drama
0,23890098,"Shlykov, a hard-working taxi driver and Lyosha...",Taxi Blues,world cinema
1,31186339,The nation of Panem consists of a wealthy Capi...,The Hunger Games,action/adventure
1,31186339,The nation of Panem consists of a wealthy Capi...,The Hunger Games,science fiction
1,31186339,The nation of Panem consists of a wealthy Capi...,The Hunger Games,action
1,31186339,The nation of Panem consists of a wealthy Capi...,The Hunger Games,drama
2,20663735,Poovalli Induchoodan is sentenced for six yea...,Narasimham,musical
2,20663735,Poovalli Induchoodan is sentenced for six yea...,Narasimham,action
2,20663735,Poovalli Induchoodan is sentenced for six yea...,Narasimham,drama
2,20663735,Poovalli Induchoodan is sentenced for six yea...,Narasimham,bollywood

In [16]:
book_counts = book_genres_exploded['genres'].value_counts()
movie_counts = movie_genres_exploded['Genre'].value_counts()

print("book")
print(book_counts.head(20))
print("movie")
print(movie_counts.head(20))

book
genres
fiction                   4747
speculative fiction       4314
science fiction           2870
novel                     2463
fantasy                   2413
children's literature     2122
mystery                   1396
young adult literature     825
suspense                   765
crime fiction              753
historical novel           654
thriller                   568
horror                     511
romance novel              435
historical fiction         388
detective fiction          341
adventure novel            330
non-fiction                230
alternate history          226
spy fiction                190
Name: count, dtype: int64
movie
Genre
drama               19134
comedy              10467
romance film         6666
thriller             6530
action               5868
world cinema         5153
crime fiction        4275
horror               4082
black-and-white      3731
indie                3668
action/adventure     3553
adventure            3248
family film          3219
short film           3192
romantic drama       2572
animation            2441
musical              2414
science fiction      2339
mystery              2119
romantic comedy      2075
Name: count, dtype: int64

In [17]:
COMMON_GENRES = [
    "drama",
    "comedy",
    "action",
    "romance",
    "thriller",
    "horror",
    "fantasy",
    "sci-fi",
    "crime",
    "mystery",
    "adventure",
    "history",
    "family"
]

In [2]:
genre_map = {

    # ---------------- DRAMA ----------------
    "drama": "drama",
    "fiction": "drama",
    "novel": "drama",
    "world cinema": "drama",
    "non-fiction": "drama",

    # ---------------- COMEDY ----------------
    "comedy": "comedy",
    "romantic comedy": "comedy",

    # ---------------- ROMANCE ----------------
    "romance": "romance",
    "romance novel": "romance",
    "romance film": "romance",
    "romantic drama": "romance",

    # ---------------- ACTION ----------------
    "action": "action",
    "action/adventure": "action",

    # ---------------- ADVENTURE ----------------
    "adventure": "adventure",
    "adventure novel": "adventure",

    # ---------------- THRILLER ----------------
    "thriller": "thriller",
    "suspense": "thriller",

    # ---------------- HORROR ----------------
    "horror": "horror",

    # ---------------- SCI-FI ----------------
    "science fiction": "sci-fi",
    "speculative fiction": "sci-fi",
    "alternate history": "sci-fi",

    # ---------------- FANTASY ----------------
    "fantasy": "fantasy",

    # ---------------- CRIME ----------------
    "crime": "crime",
    "crime fiction": "crime",

    # ---------------- MYSTERY ----------------
    "mystery": "mystery",
    "detective fiction": "mystery",

    # ---------------- HISTORY ----------------
    "historical fiction": "history",
    "historical novel": "history",

    # ---------------- FAMILY ----------------
    "children's literature": "family",
    "family film": "family",
    "young adult literature": "family",

    # ---------------- SPECIAL CASES ----------------
    "animation": "family",
    "musical": "romance",
    "spy fiction": "thriller"
}

In [3]:
#format removal
invalid_genres = {
    "black-and-white",
    "short film",
    "indie"
}

In [4]:
def map_genres(genres):
    mapped = []
    for g in genres:
        g = g.lower().strip()
        
        if g in invalid_genres:
            continue
            
        if g in genre_map:
            mapped.append(genre_map[g])
    
    return list(set(mapped))

In [21]:
df_book['mapped_genres'] = df_book['genres'].apply(map_genres)
df_movie['mapped_genres'] = df_movie['Genre'].apply(map_genres)

In [22]:
df_book.explode('mapped_genres')['mapped_genres'].value_counts()
df_movie.explode('mapped_genres')['mapped_genres'].value_counts()

mapped_genres
drama        20733
comedy       10726
romance       8448
action        6781
thriller      6574
family        4419
crime         4297
horror        4082
adventure     3248
sci-fi        2339
mystery       2158
fantasy       2012
history        305
Name: count, dtype: int64

In [23]:
print(df_book.columns)
print(df_movie.columns)

Index(['title', 'genres', 'summary', 'mapped_genres'], dtype='object')
Index(['id', 'plot', 'name', 'Genre', 'mapped_genres'], dtype='object')

In [24]:
df_movie = df_movie.rename(columns={'plot': 'summary'})

In [ ]:
# df_movie = df_movie.rename(columns={'name': 'title'})

In [25]:
df_book['form']='book'
df_movie['form']='movie'

In [26]:
# books=df_book[['summary','mapped_genres','form','title']]
# movies=df_movie[['summary','mapped_genres','form','title']]
books=df_book[['summary','mapped_genres','form']]
movies=df_movie[['summary','mapped_genres','form']]


movies.head()

,summary,mapped_genres,form
0,"Shlykov, a hard-working taxi driver and Lyosha...",[drama],movie
1,The nation of Panem consists of a wealthy Capi...,"[sci-fi, action, drama]",movie
2,Poovalli Induchoodan is sentenced for six yea...,"[action, drama, romance]",movie
3,"The Lemon Drop Kid , a New York City swindler,...",[comedy],movie
4,Seventh-day Adventist Church pastor Michael Ch...,"[drama, crime]",movie

In [27]:
cmu_dataset=pd.concat([books,movies],ignore_index=True)

In [28]:
cmu_dataset = cmu_dataset.reset_index(drop=True)

In [29]:
cmu_dataset.shape

(55045, 3)

In [30]:
cmu_dataset.describe()

                                     summary mapped_genres   form
count                                  55045         55045  55045
unique                                 55013          1221      2
top      ~Plot outline description~ --> <!--       [drama]  movie
freq                                      13          8676  42204

In [31]:
cmu_dataset= cmu_dataset.rename(columns={'mapped_genres': 'genres'})

In [32]:
cmu_dataset.head()

,summary,genres,form
0,"Old Major, the old boar on the Manor Farm, ca...","[sci-fi, drama, family]",book
1,"Alex, a teenager living in near-future Englan...","[sci-fi, drama]",book
2,The text of The Plague is divided into five p...,[drama],book
3,The novel posits that space around the Milky ...,"[sci-fi, fantasy, drama]",book
4,"The book tells the story of Paul Bäumer, a Ge...",[],book

In [33]:
cmu_dataset=cmu_dataset[cmu_dataset['genres'].map(len)>0]

In [34]:
cmu_dataset.shape

(49827, 3)

In [ ]:
# cmu_dataset.drop(['title'],inplace=True,axis=1)

In [35]:
cmu_dataset.columns

Index(['summary', 'genres', 'form'], dtype='object')

In [5]:
book_movie_1=pd.read_csv('/kaggle/input/datasets/adithip2000/cmu-dataset/bm.csv')
book_movie_2=pd.read_csv('/kaggle/input/datasets/adithip2000/cmu-dataset/bm2.csv')

In [6]:
book_movie_1=book_movie_1.rename(columns={'domain': 'form'})
book_movie_2=book_movie_2.rename(columns={'domain': 'form'})

In [7]:
book_movie_1.head()

,Unnamed: 0,summary,genres,form
0,0,A tragic tale of a wealthy law student who des...,"['drama', 'romance']",book
1,1,A high-drama musical adaptation highlighting t...,"['drama', 'musical', 'romance']",movie
2,2,A semi-autobiographical novel depicting the st...,"['drama', 'coming-of-age']",book
3,3,"Satyajit Ray's directorial debut, capturing th...","['drama', 'art-house']",movie
4,4,"The story of Raju, a corrupt tour guide who un...","['drama', 'philosophical']",book

In [8]:
book_movie_2.columns

Index(['Unnamed: 0', 'summary', 'genres', 'form'], dtype='object')

In [9]:
book_movie_1.drop(['Unnamed: 0'],inplace=True,axis=1)
book_movie_2.drop(['Unnamed: 0'],inplace=True,axis=1)

In [10]:
print(type(book_movie_1['genres'].iloc[0]))

<class 'str'>

In [11]:
import ast
book_movie_1['genres']=book_movie_1['genres'].apply(ast.literal_eval)
book_movie_2['genres']=book_movie_2['genres'].apply(ast.literal_eval)

In [12]:
bk_1 = book_movie_1.explode('genres')
bk_2 = book_movie_2.explode('genres')

book_counts = bk_1['genres'].value_counts()
movie_counts = bk_2['genres'].value_counts()

print("bk1")
print(book_counts.head(20))
print("bk2")
print(movie_counts.head(20))

bk1
genres
drama            102
romance           42
thriller          40
historical        27
sci-fi            22
biographical      20
crime             19
comedy            19
horror            19
adventure         17
mystery           15
fantasy           13
tragedy           13
action            10
psychological      8
sports             5
dystopian          5
musical            4
coming-of-age      4
fiction            4
Name: count, dtype: int64
bk2
genres
drama               27
romance              6
thriller             5
social-issue         5
historical           4
fiction              3
crime                3
autobiographical     3
action               3
art-house            2
comedy               2
family               2
survival             2
biographical         2
period               1
tragedy              1
feminist             1
musical              1
epic                 1
coming-of-age        1
Name: count, dtype: int64

In [13]:
genre_map_extra = {

    # ---------------- DRAMA ----------------
    "fiction": "drama",
    "tragedy": "drama",
    "social-issue": "drama",
    "art-house": "drama",
    "feminist": "drama",

    # ---------------- HISTORY ----------------
    "historical": "history",
    "biographical": "history",
    "autobiographical": "history",
    "period": "history",

    # ---------------- THRILLER ----------------
    "psychological": "thriller",

    # ---------------- SCI-FI ----------------
    "dystopian": "sci-fi",

    # ---------------- FAMILY ----------------
    "coming-of-age": "family",

    # ---------------- ADVENTURE ----------------
    "survival": "adventure",
    "epic": "adventure",

    # ---------------- ROMANCE ----------------
    # already covered

    # ---------------- MUSICAL ----------------
    "musical": "romance",  # or drama (either is fine, keep consistent)

    # ---------------- SPORTS ----------------
    "sports": "drama"
}

In [14]:
genre_map.update(genre_map_extra)

In [15]:
book_movie_1['genres'] = book_movie_1['genres'].apply(map_genres)
book_movie_2['genres'] = book_movie_2['genres'].apply(map_genres)

In [16]:
bk_1 = book_movie_1.explode('genres')
bk_2 = book_movie_2.explode('genres')

book_counts = bk_1['genres'].value_counts()
movie_counts = bk_2['genres'].value_counts()

print("bk1")
print(book_counts.head(20))
print("bk2")
print(movie_counts.head(20))

bk1
genres
drama        110
romance       44
thriller      44
history       41
adventure     21
crime         19
comedy        19
horror        19
mystery       15
fantasy       13
action        10
sci-fi         5
family         4
Name: count, dtype: int64
bk2
genres
drama        28
history      10
romance       6
thriller      6
action        3
adventure     3
crime         3
comedy        2
family        1
Name: count, dtype: int64

In [17]:
bk_1.shape

(365, 3)

In [18]:
bk_2.shape

(62, 3)

In [20]:
bk_2.to_csv('/kaggle/working/test_cmu_data.csv')

In [57]:
fully_combined_data=pd.concat([cmu_dataset,book_movie_1,book_movie_2],ignore_index=True)

In [61]:
fully_combined_data.shape

(50048, 4)

In [60]:
fully_combined_data=fully_combined_data[fully_combined_data['genres'].map(len)>0]

In [62]:
bk_1 = fully_combined_data.explode('genres')
book_counts = bk_1['genres'].value_counts()
print("bk1")
print(book_counts.head(20))

bk1
genres
drama        27291
comedy       10894
romance       8933
thriller      7947
sci-fi        7561
family        7100
action        6794
crime         5072
horror        4612
fantasy       4438
mystery       3633
adventure     3605
history       1228
Name: count, dtype: int64

In [63]:
fully_combined_data.to_csv('book_movie_combined.csv')